// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dpjzrtwahmbnlxmwnuvc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRwanpydHdhaG1ibmx4bXdudXZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1NTIzMzMsImV4cCI6MjA2OTEyODMzM30.Mga7qsXM390FSz8bAQa2xXSOer65FWG2ezFKSffVAg0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});